### PR TITLE
Definition of Done

### PR DESCRIPTION
**Pull request by christinamattinson**
### Blog title
All for One, Definition of Done
### Blog description
Some observations and learnings on how we implement Definition of Done at HX

#### Author
- [ ] I have checked for grammatical errors
- [ ] I have checked for spelling errors
- [ ] All information (technical or otherwise) is correct to my knowledge

#### Editor 1
- [x] I have checked for grammatical errors
- [x] I have checked for spelling errors
- [x] All information (technical or otherwise) is correct to my knowledge

#### Editor 2
- [ ] I have checked for grammatical errors
- [ ] I have checked for spelling errors
- [ ] All information (technical or otherwise) is correct to my knowledge

### CODE REVIEW

**Comment by gozzatron** [comment]
I'll take the first review

**Comment by gozzatron** [comment]
1st paragraph.
> Remove capital 'P' in Please within the bracket.
> Link to scrum alliance page is broken. 
> Missing close bracket next to the link.

2nd paragraph
> Missing comma after Definition of Done
> .... Web team of 88 broken down into 13 scrum teams.... - should be a comma after 88, or should it be rephrased to read "....we have a team of 88, broken down in 13 scrum teams....?"

3rd Paragraph
> Change 'there' to 'their' in the first line. 

4th Paragraph
> Change 'to much' to 'too much' in the opening sentence.

**Comment by christinamattinson** [comment]
All done thanks Steve!

**Comment by gozzatron** [comment]
Signing off :+1:

**Comment by christinamattinson** [comment]
I am closing this as I woke up this morning and want to re-write parts.

**Comment by hpoom** [comment]
I was about to feedback, but if you are going to rewrite parts I will wait for the rewrite.

Sorry I took so long to look at it. Send the new version my way when you have it.

**Pull request closed without merging**
