### PR TITLE
Posts padding

### PR DESCRIPTION
**Pull request by jodiedoubleday**
### What does this PR do?
- Increases the padding at the top of the posts (home) page.

### What is the issue your trying to solve?
screen shot 2015-02-19 at 12 24 49
- The styling (white up arrow, which is actually a square, not sure why) overlaps the content below.
- A quick fix just adds padding, I don't have the time (just yet) to change this to a triangle.

#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this on mobile Android, Safari, Chrome for any visual changes.
- [x] I am ready for this to be code reviewed, merged and tested.

#### IP or Developer Review:
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve checked for coding anti-patterns.
- [x] +1 from me!

#### Software Engineer, Software Architect or Developer review:
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve checked for coding anti-patterns.
- [x] +1 from me!

### CODE REVIEW

**Comment by Joezo** [comment]
:+1:

**Comment by jackdcrawford** [comment]
Yup :+1:

**Comment by dancork** [comment]
@jodiedoubleday just had a quick play in web inspector. you can achieve this with...

```header:after {
content: "";
width: 0;
height: 0;
position: absolute;
left: 50%;
right: 50%;
bottom: 0;
margin-left: -28px;
border-bottom: 28px solid #fff;
border-left: 28px solid transparent;
border-right: 28px solid transparent;```

**Comment by jodiedoubleday** [comment]
Hey @dancork yup, knew you could do it but don't have the time to adjust this just yet so was putting in a quick fix in this PR, which also aligns the padding up with the general post page anyway.
Fancy putting your fix in a PR?

**Comment by jodiedoubleday** [comment]
Cool, all changed

**Pull request merged**
