### PR TITLE
new post - A fresh look at Agile

### PR DESCRIPTION
**Pull request by storer**
### Blog title

A Fresh look at Agile

### Blog description

Briefly summarises the approach we take to agile. What makes the process work. What makes it better.

#### Author
- [X] I have checked for grammatical errors
- [X] I have checked for spelling errors
- [X] All information (technical or otherwise) is correct to my knowledge

#### Editor 1
- [x] I have checked for grammatical errors
- [x] I have checked for spelling errors
- [x] All information (technical or otherwise) is correct to my knowledge

#### Editor 2
- [x] I have checked for grammatical errors
- [x] I have checked for spelling errors
- [x] All information (technical or otherwise) is correct to my knowledge

### CODE REVIEW

**Comment by storer** [comment]
@jodiedoubleday @jackdcrawford  Up for review - if you please.

**Comment by lizpope** [comment]
I've taken the Editor 1 Review. 
I've read through - really like the post, some great content. Grammatically/spelling etc all good too

**Comment by jodiedoubleday** [comment]
Taking Editor 2

**Comment by andrewcashmore** [comment]
Happy with this :+1: - @jodiedoubleday took the review in your absence

**Pull request merged**
