### PR TITLE
Launching New Products Takes Teamwork - new blog post

### PR DESCRIPTION
**Pull request by carolinewoodhams**
### Blog title
Launching New Products Takes Teamwork

### Blog description 
Launching new products takes teamwork. This post explores the relationship with Sales (Partnerships team). 

#### Author
Caroline
- [x] I have checked for grammatical errors
- [x] I have checked for spelling errors
- [x] All information (technical or otherwise) is correct to my knowledge

#### Editor 1
- [x] I have checked for grammatical errors
- [x] I have checked for spelling errors
- [x] All information (technical or otherwise) is correct to my knowledge

#### Editor 2
- [x] I have checked for grammatical errors
- [x] I have checked for spelling errors
- [x] All information (technical or otherwise) is correct to my knowledge

### CODE REVIEW

**Comment by steve-at-hx** [comment]
Will review before the end of the week!

**Comment by hxmattobee** [comment]
Taking 2️⃣

**Comment by hxmattobee** [comment]
👍  I like it @carolinewoodhams.

**Comment by steve-at-hx** [comment]
Sorry for the delay. I _think_ this is what we spoke about yesterday!

- Paragraph starting "Whilst the New Products pod..." I had to read a few times before it sunk in and I think it's making some of the key points. You mentioned when we spoke about there being two sides of the coin. Perhaps an analogy would support that paragraph?
- There are some interesting distinctions to be made either in this post or later in the series about the advantages and disadvantages of being an intrepreneurial team in an established business. For example doors being opened that wouldn't otherwise, but having a strong brand that needs protecting.
- One example of the above that could maybe be incorporated in to this post is that established relationships with clients and open communication channels gives us an opportunity to get great qualitative feedback where a traditional startup would be largely dependent on quantitative. 

We spoke about more, but hopefully this is a flavour! As discussed, maybe apart from that first point, nothing needs to change in this version, but it might be worth alluding to it to build anticipation for further posts and show that it has been considered.

**Comment by steve-at-hx** [comment]
I'm not sure I support this statement:
> Don’t wait to ship until everybody on the development team’s ‘ready’: perfect code, zero technical debt, a million and one features...
My view on MVP is that it should be de-scoped in terms of features, not quality. In saying that, it's opinion/interpretation so you shouldn't let this stop you publishing unless you want a discussion around it first, so I'm happy to +1.

**Pull request merged**
