### PR TITLE
Atom feed for posts in the Testing category

### PR DESCRIPTION
**Pull request by hxmattobee**
#### What does this PR do? (please provide any background)
We already had an Atom feed (`feed.xml`) that supplied a feed of the 10 most recent blog posts across all categories. I've been asked to supply a feed of posts in the Testing category so that they can be syndicated by Ministry of Testing. I have therefore created a second Atom feed (`testing-feed.xml`) that does the job using `{% for post in site.categories.testing limit:10 %}`.

#### What tests does this PR have?
N/a

#### How can this be tested?
Look at the newly created `testing-feed.xml` in a text editor, or open it in your browser to check that it is parsed correctly.

#### What gif best describes how you feel about this work?

---

- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.

#### Reviewers

**Review 1**
- [x] :+1:

**Review 2** \*
- [ ] :+1:

**Review 3** _(optional)_
- [ ] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

\*  for HX this review must be completed by an SE, SA or Project Guru

### CODE REVIEW

**Comment by dancork** [comment]
Just a thought, might be more beneficial long term to adapt the main feed to accept a category param.

**Comment by hxmattobee** [comment]
Agreed @dancork. I had a look and couldn't see a quick way to do it directly in Jekyll. Would it need to be handled by the routing? May well be beyond the scope of what I need and what I can do in the short term.

**Comment by dancork** [comment]
Yeh, for now this is the better solution. :+1:

**Comment by jackdcrawford** [comment]
:+1:

**Pull request merged**
