### PR TITLE
Added syntax highlighting to code blocks

### PR DESCRIPTION
**Pull request by Joezo**
#### What does this PR do?
Adds syntax highlighting to code blocks within our posts.
#### What unit or integration tests does this PR have?
None
#### What selenium tests does this PR have?
None
#### How should a developer review this?
Check that the changes i've made make sense, i'm not 100% sure on making a new html file to include a script tag. What do others think?
#### How should this be manually tested?
Run this branch locally and visit a post like harleys express tutorial, you should see all the code snippets have been highlighted.
#### What gif best describes how you feel about this work?

---
#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've checked there is appropriate unit test coverage.
- [x] I've checked there is appropriate selenium test coverage.
- [x] I've included regression tests for any bug fixes.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this on mobile Android, Safari, Chrome for any visual changes.
- [x] I've tested this on desktop IE9/10/11, Firefox, Chrome for any visual changes.
- [x] I've checked any significant visual changes with a member of the UX/UI pod.
- [x] I've checked this work against the requirements of the Jira.
- [x] I've added and updated translations for all supported languages
- [x] I've informed those who need to know of any unforeseen impact of this work (database migrations, deployment procedure changes).
- [x] I am ready for this to be code reviewed, merged and tested.
- [x] I've thought about writing a blog post about this

#### IP or Developer Review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] +1 from me!

#### Software Engineer or Developer review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] +1 from me!

#### Software Engineer or project guru review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!

### CODE REVIEW

**Comment by jodiedoubleday** [comment]
taking SE

**Comment by jodiedoubleday** [comment]
:+1:

**Comment by stuartstobie** [comment]
This sounds like a great idea, I'll take the IP review.

**Comment by stuartstobie** [comment]
Changes look solid, are there any tests to be run here? If not it's a +1 from me.

**Comment by jackdcrawford** [comment]
`takeDevSlot();`

**Comment by jackdcrawford** [comment]
:+1: yes

**Pull request merged**
