### PR TITLE
Iphone pain

### PR DESCRIPTION
**Pull request by jodiedoubleday**
## What does this PR do?
- Adds prefixing for old mobile phones like iPhone :trollface: 
- Also adds prefixing for opera, ie and firefox

## How to test
- Checkout branch
- Run `jekyll serve --safe` this should boot up the blog locally
- Visit your IP address (localhost) on your phone (:4000/)
- ENSURE The team photos don't look like this
slack_for_ios_upload_1024

### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've updated documentation with any changes to procedures..
- [x] I am ready for this to be code reviewed, merged and tested.

#### IP or Developer Review:
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve checked for coding anti-patterns.
- [x] +1 from me!

#### Software Engineer, Software Architect or Developer review:
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve checked for coding anti-patterns.
- [x] +1 from me!

### CODE REVIEW

**Comment by andrew-c** [comment]
@jodiedoubleday Looks like this for me? Not sure if that's what you expect (iPhone 6). https://cloudup.com/cqHT0QKmNJQ

**Comment by jodiedoubleday** [comment]
thats exactly what it should look like :)

**Comment by andrew-c** [comment]
:+1: Then

**Comment by andrewcashmore** [comment]
:+1: looks good

**Pull request merged**
