### PR TITLE
Changing UX designer to UI designer

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)
We are getting a lot or research UXers applying for the jobs we are advertising, so to get the kinda of people we want (more design focussed) we are changing our job ad to ask for a *User Interface designer*

#### What tests does this PR have?
None

#### How can this be tested?
run `jekyll serve` then visit 

#### Screenshots / Screencast
screen shot 2015-11-13 at 16 27 09

#### What gif best describes how you feel about this work?
trippy

---

- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Reviewers

**Review 1**
- [x] :+1:

**Review 2** \*
- [x] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.

### CODE REVIEW

**Comment by dancork** [comment]
Taking review

**Comment by dancork** [comment]
Still a few mentions of UX? Just changing the title?

**Comment by hpoom** [comment]
:+1:

**Comment by jodiedoubleday** [comment]
Yup i think the mention of 'right UX tools' is still valid

**Comment by dancork** [comment]
:+1:

**Pull request merged**
