### PR TITLE
Fixing broken links

### PR DESCRIPTION
**Pull request by jodiedoubleday**
## What does this PR do?
Having looked at Google Webmaster tools we have a lot of broken links
screen shot 2015-04-24 at 12 14 58

- This fixes a lot of the simple broken links on blog posts
- This adds in Dan Jenkins to the authors but lists him as no longer HX

## How to test
- Checkout branch
- Run `jekyll serve`
- Visit `http://localhost:4000`
- Check out the individual changes in the code and ensure that the links now work properly
- Make sure Jan Jenkins has a picture but doesn't appear on the team page

## Give me a GIF
fix you

#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've updated documentation with any changes to procedures..
- [x] I am ready for this to be code reviewed, merged and tested.

#### IP or Developer Review:
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve checked for coding anti-patterns.
- [x] +1 from me!

#### Software Engineer, Software Architect or Developer review:
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve checked for coding anti-patterns.
- [x] +1 from me!

### CODE REVIEW

**Comment by jackdcrawford** [comment]
Taking the developer review

**Comment by Joezo** [comment]
taking the other review

**Comment by Joezo** [comment]
:+1:

**Comment by jackdcrawford** [comment]
Looks good to me :+1:

**Pull request merged**
