### PR TITLE
Moved Caroline's SIPOC blog from drafts to post

### PR DESCRIPTION
**Pull request by LouisPryer**
#### Author
- [x] I have checked for grammatical errors
- [x] I have checked for spelling errors
- [x] All information (technical or otherwise) is correct to my knowledge

#### Editor 1
- [ ] I have checked for grammatical errors
- [ ] I have checked for spelling errors
- [ ] All information (technical or otherwise) is correct to my knowledge

#### Editor 2
- [ ] I have checked for grammatical errors
- [ ] I have checked for spelling errors
- [ ] All information (technical or otherwise) is correct to my knowledge

### CODE REVIEW

**Comment by LouisPryer** [comment]
@carolinewoodhams Great read, I have a few grammar suggestions and changes in the header of the file to file in some of the extra details in the page.

- I would remove the `published` key before this goes live
- For your profile to go through on the page, you will need to match it with the key inside of the [members file](https://github.com/holidayextras/holidayextras.github.com/blob/master/_data/members.yml), changing it to `caroline_woodhams` will sort it out for you
- With the tags, I don't think it will play ball with the `>-` you have in that field. If you set them out with commas similar to [Steve's Post](https://github.com/holidayextras/holidayextras.github.com/blame/master/_posts/2017-02-02-time-to-talk-2017.md#L6) then it should be fine
- > SIPOC is useful at multiple stages of product development, but is especially powerful
  - Should that be "but it is..."?
- > (or assumptions may be made!)
  - Full stop after the brackets (ignore me if you think this is right)
- In the WHY use a SIPOC section, do we want to use bullet points for last part?

<sidenote>More of a question but in the "Who needs to be there?" part, were any of the testers involved? Just curious not a suggestion</sidenote>

Let me know what you think. Cheers, Louis.

**Comment by carolinewoodhams** [comment]
Hey Louis, thanks for taking the time to review this!

The 'published' key and tags formatting is as a result of using Prose.io - I didn't insert those bits myself. 

I've updated my name so it should pull through now :)

For grammar:
- don't need to use 'it' - it's clear what I'm referring to and it would be superfluous
- you don't use punctuation after brackets - the punctuation within the brackets does the job for you :)
- yes, I was trying to use bullet points, I guess that piece of formatting got missed in the conversion to a PR too. Could you help me sort it out please? I always struggle with lists in markdown (know what they are in HTML!)

We don't have a tester in INT pod - Beard is helping us with ad hoc bits, but he wasn't there for this session. 

If you could check over the changes, help me with the bullets, then I think it's ready to go :)

**Comment by carolinewoodhams** [comment]
Updated the bullets following Louis' advice, committed changes.

**Comment by LouisPryer** [comment]
👍

**Pull request merged**
