### PR TITLE
Increase font-size, pagination and visibility

### PR DESCRIPTION
**Pull request by jodiedoubleday**
## What does this PR do?
- Increases the font size of the whole website.
- Add profile pictures to the homepage
- Truncates post summary to 50 words
- Increases posts per page to 10 (pagination)

## How to test
- Checkout branch
- Run `jekyll serve`
- Visit `http://localhost:4000`
- Text should be bigger
- Profile pictures should appear next to each summary
- Posts are truncated to 50 words
- There are now 10 posts per page.

## Give me a GIF
doggie

#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've updated documentation with any changes to procedures..
- [x] I am ready for this to be code reviewed, merged and tested.

#### IP or Developer Review:
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve checked for coding anti-patterns.
- [x] +1 from me!

#### Software Engineer, Software Architect or Developer review:
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve checked for coding anti-patterns.
- [x] +1 from me!

### CODE REVIEW

**Comment by jackdcrawford** [comment]
I shall take the IP/Dev review

**Comment by jackdcrawford** [comment]
All the things you said all the things you said work on my machine work on my machine WORK ON MY MACHINE

:+1:

**Comment by cameronviner** [comment]
Taking DEV

**Comment by cameronviner** [comment]
Increases the font size of the whole website. - Yep font is bigger now
Add profile pictures to the homepage - Yep can see everyones face
Truncates post summary to 50 words - I counted and got exactly 50 words in the description
Increases posts per page to 10 (pagination) - There were 10 posts per page.

I did notice that one of the articles doesn't have a description: http://grab.by/GzRG but im guessing that is  due to how that post was written rather than these changes.

Looks good +1

**Pull request merged**
