### PR TITLE
Fix line height on mobile and date error

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do?
- Adjusts Annas post to include a link rather than just text to a website
- Adjust the line height for the heading on mobile to make them more readable (see below)
- Removes CURRENT_DATETIME which doesn't work in prose.io
- Adjust the margin of blog posts so the white arrow doesn't overlap the posts first sentence (see picture above)

#### How should a developer review this?
- Pull the branch
- run `jekyll serve -- drafts` (if your ont have jekyll install please view readme)

#### How should this be manually tested?
As above

#### Any background context you want to provide?
A blog post went live with a few errors, this PR fixes those error on the live posts

#### Screenshots (if appropriate)
screen shot 2015-01-15 at 14 56 49

#### What gif best describes how you feel about this work?
angry

---
#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this on mobile Android, Safari, Chrome for any visual changes.
- [x] I am ready for this to be code reviewed, merged and tested.

#### IP or Developer Review:
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve checked for coding anti-patterns.
- [x] +1 from me!

#### Software Engineer, Software Architect or Developer review:
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve checked for coding anti-patterns.
- [x] +1 from me!

### CODE REVIEW

**Comment by jackdcrawford** [comment]
I can take the Dev/SE slot

**Comment by jackdcrawford** [comment]
Looks good! :neckbeard::+1: 

good

**Comment by Joezo** [comment]
:+1:

**Comment by michaelcarter** [comment]
I can take SE/Guru.

**Aside:** Should our blogging platform need to be subject to the same rigorous PR process our customer facing money making code? Feels like we're doing it wrong if we need to code review changes rather than just proof reading things a couple of times and pushing a "publish" button.

**Comment by jodiedoubleday** [comment]
Hello @michaelcarter  it doesn't, you are right, i have made a markdown template for reviewing blog posts and editing the code of the blog, but I'm yet to finalise these, share them and put them in the hx-culture repo. So I use the existing one for the moment.
It's on my list.

**Comment by michaelcarter** [comment]
I'm getting the following error trying to run this. I've followed the readme instructions, and having used Jekyll in the past it looks like it should be that easy, but it doesn't seem to be working for me. :(

```
03:00 pm ~/work/holidayextras.github.com (master|✚ 1) $ jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      posix-spawn (~> 0.3.6)
      redcarpet (~> 3.1)
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:21:in `block in <top (required)>': cannot load such file -- jekyll/version (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'
```

**Pull request merged**
