### PR TITLE
Updated the install info and the gemlock file

### PR DESCRIPTION
**Pull request by robhuzzey**
Hey all,

I had a few issues getting this working locally so after a bit of reading it turns out I should have ran ```bundle install``.
see: http://bundler.io/v1.3/rationale.html#checking-your-code-into-version-control

I've updated the README.md & the gemlock file so the next developer shouldn't have issues.

#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this on mobile, tablet and desktop for any visual changes.
- [x] I am ready for this to be code reviewed, merged and tested.

#### IP or Developer Review:
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve checked for coding anti-patterns.
- [x] +1 from me!

#### Software Engineer, Software Architect or Developer review:
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve checked for coding anti-patterns.
- [x] +1 from me!

### CODE REVIEW

**Comment by jodiedoubleday** [comment]
Not sure you should commit the ``browserconfig.xml``` or the ```gemfile.lock``` are they not auto generated?
If not maybe we should create a gitignore?

**Comment by robhuzzey** [comment]
@jodiedoubleday I read up on gemfile.lock & this link pretty much says commit it: http://bundler.io/v1.3/rationale.html#checking-your-code-into-version-control this way you can re-create the snapshot of when the application last worked.

**Comment by jodiedoubleday** [comment]
schweet cheers @robhuzzey

**Comment by jodiedoubleday** [comment]
Looks good, works well solves a lot of issues :+1: :neckbeard:

**Comment by lukefrake** [comment]
+1... let's merge this :)

**Comment by lukefrake** [comment]
Unless... We want to just tell people to do it the same as Github do it?

https://help.github.com/articles/using-jekyll-with-pages/

Might stop inconstancies in the future?

**Comment by robhuzzey** [comment]
@lukefrake I've merged now... that's not a bad shout but I'd say it could add unnecessary confusion? Do a PR for it.

**Pull request merged**
